#--------------- Define your email, file, and settings details here
# Set up the IMAP connection
IMAP_SERVER: imap.gmail.com
IMAP_PORT: 993
SMTP_SERVER: smtp.gmail.com
SMTP_PORT: 587
# Set up your email credentials
SMTP_USERNAME: sk0551460@gmail.com
SMTP_PASSWORD: htao qlqy ysex zqyb
# Name of the Email Sender
SENDER_NAME: Shivam
DRIVER_NAME: ODBC Driver 17 for SQL Server    # Choose the ODBC driver for your SQL Server
SERVER_NAME: LAPTOP-UG5R2KF5\SQLEXPRESS  #your SQL SERVER name
DATABASE_NAME: onlyjobs    # DATABASE NAME
USERNAME: Onlyjobs_sa     # Replace with the SQL Server username you created
PASSWORD: Onlyjobs_sa@123 # Replace with the corresponding password